### ISSUE TITLE
winfetch glitched

### ISSUE THREAD

**Issue by emilianpr** [M4cs/winfetch#14]
![Immagine 2022-07-10 003056](https://user-images.githubusercontent.com/64985601/178124635-0d550159-2f2e-4918-81be-f4138348d7bc.png)

is there a way to fix this?

this happens on powershell and command prompt

**Comment by mrplayergod** [comment]
Skill issue?

**Comment by M4cs** [comment]
You'll need to use a different font or terminal. I believe this happens when your terminal doesn't support XTerm colors
