### ISSUE TITLE
Image in low resolution or overshadowed

### ISSUE THREAD

**Issue by Quike45** [M4cs/winfetch#15]
Hello, I have a problem with Winfetch when I want to put an image on the cover, it all comes out pixelated and blurry, if someone knows the solution it would be of great help, thanks

--it has been in all the images I've put--
-- The images are in PNG and Jpg formats. ---

![imagen_2022-11-13_011241900](https://user-images.githubusercontent.com/117871380/201508512-f4f153d0-d2e4-4293-ae48-f822b0c1ddab.png)
![imagen_2022-11-13_011249858](https://user-images.githubusercontent.com/117871380/201508517-014f777d-b4ea-4d5e-815c-eeafab1d1412.png)
![imagen_2022-11-13_011342101](https://user-images.githubusercontent.com/117871380/201508534-aef58d4f-ddc3-4269-82c0-37b6c708e5e1.png)
![imagen_2022-11-13_011417766](https://user-images.githubusercontent.com/117871380/201508538-9e9ee561-866f-4b02-8655-51c4ca4a6b6a.png)

**Comment by WernCoreOfficial** [comment]
it is supposed to be like this
